---
title: "Final project"
author: "YU SUN"
date: "4/19/2019"
output: pdf_document
---
```{r}
library(ggplot2)
library(dplyr)
library(tidyverse)
```

```{r}
data <- read.csv('/Users/sunyu/Desktop/IE 6600/final_project/Airplane_Crashes_and_Fatalities_Since_1908.csv',sep = ',',,stringsAsFactors = FALSE)
```


```{r}
head(data)

data %>%
  drop_na() %>%
  group_by(Operator)


```
```{r}

any(data$Operator=='')
dataNoNA <- data %>% 
  filter(Operator != '') %>%
  filter(Fatalities != '')%>%
  filter(Aboard != '')%>%
  filter(!is.na(Fatalities))


# as.data.frame(data)


opStat <- dataNoNA %>%
  group_by(Operator) %>%
  summarise(totalFatalities = sum(Fatalities), numAccidents = n())


# any(data$Operator=='')
# aggregate(data$Fatalities, by=list(Operator=data$Operator), FUN=sum)

# class(data)

# Python 的第一张图
opStat %>%
  arrange( desc(totalFatalities)) %>%
  head(10) %>%
  ggplot(aes(x = reorder(Operator, -totalFatalities),totalFatalities, fill = Operator)) +
  geom_bar(stat = "identity") + 
  xlab("Operators") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)) +
  theme(legend.position = "none")

# Python 的竖着第二张图
opStat %>%
  arrange( desc(totalFatalities)) %>%
  head(10) %>%
  ggplot(aes(x = reorder(Operator, -numAccidents),numAccidents, fill = Operator)) +
  geom_bar(stat = "identity") + 
  xlab("Operators") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)) +
  theme(legend.position = "none")

# Python 的比例图
ntf = sum(opStat$totalFatalities)
opStat$totalFatalitiesProp <- opStat$totalFatalities/ntf

nacc = sum(opStat$numAccidents)
opStat$numAccidentsProp <- opStat$numAccidents/nacc

# check the correctness of proportion
# sum(opStat$totalFatalities/ntf)

# totalFatalities 的比例图
opStat %>%
  arrange( desc(totalFatalitiesProp)) %>%
  head(10) %>%
  ggplot(aes(x = reorder(Operator, -totalFatalitiesProp), totalFatalitiesProp, fill = Operator)) +
  geom_bar(stat = "identity") + 
  xlab("Operators") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)) +
  theme(legend.position = "none")

# numAccidents 比例图
opStat %>%
  arrange( desc(totalFatalities)) %>%
  head(10) %>%
  ggplot(aes(x = reorder(Operator, -numAccidentsProp), numAccidentsProp, fill = Operator)) +
  geom_bar(stat = "identity") + 
  xlab("Operators") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)) +
  theme(legend.position = "none")


```

```{r}
# number of accidents each year
library(lubridate)

temp <- dataNoNA %>%
  filter(Operator == 'Aeroflot') %>%
  mutate(Year = year(mdy(Date))) %>%
  group_by(Year) %>%
  summarise(numAcc = n()) 


temp_full <- data.frame(Year = seq(1945,2010,1))
temp_full <- merge(temp_full, temp, all.x=TRUE)
temp_full$numAcc[is.na(temp_full$numAcc)] <- 0

temp_full %>%
  ggplot() +
  geom_line(aes(Year, numAcc, colour = 'Red')) + 
  geom_point(aes(Year, numAcc, colour = 'Red')) +
  #geom_vline(xintercept = 1973, linetype = 'dashed')
  geom_segment(aes(x = 1973, y = 15, xend = 1973, yend = -Inf), linetype = 2) +
  scale_x_continuous(breaks=seq(1945, 2010,5)) +
  scale_y_continuous(breaks=seq(0, 15, 1)) +
  theme_classic() +
  theme(legend.position = "none")


#month()
```
```{r}
# number of fatalities each year
temp2 <- dataNoNA %>%
  filter(Operator == 'Aeroflot') %>%
  mutate(Year = year(mdy(Date))) %>%
  group_by(Year)%>%
  summarise(Fatalities_num = sum(Fatalities))
temp_full2 <- data.frame(Year = seq(1945,2010,1))
temp_full2 <- merge(temp_full2, temp2, all.x=TRUE)
temp_full2$Fatalities_num[is.na(temp_full2$Fatalities_num)] <- 0
temp_full2 %>%
  ggplot() +
  geom_line(aes(Year,Fatalities_num , colour = 'Red')) + 
  geom_point(aes(Year, Fatalities_num, colour = 'Red')) +
  #geom_vline(xintercept = 1973, linetype = 'dashed')
  geom_segment(aes(x = 1973, y = 830, xend = 1973, yend = -Inf), linetype = 2) +
  scale_x_continuous(breaks=seq(1945, 2010,5)) +
 # scale_y_continuous(breaks=seq(0, 15, 1)) +
  theme_classic() +
  theme(legend.position = "none")



#month()
```

```{r} 
# temp3 is normal Operator(commerical) year range: 1908 to 2008
# number of accidents 
temp_normal <- dataNoNA %>%
  filter(!grepl("Military", Operator, fixed = TRUE))%>%
  #filter(Operator == 'Aeroflot') %>%
  mutate(Year = year(mdy(Date))) %>%
  group_by(Year)%>%
  summarise(numAcc_full = n())
temp_full3 <- data.frame(Year = seq(1945,2010,1))
temp_full3 <- merge(temp_full3, temp_normal, all.x=TRUE)
temp_full3$numAcc_full[is.na(temp_full3$numAcc_full)] <- 0

# number of fatalities

temp_fatalities <- dataNoNA %>%
  filter(!grepl("Military", Operator, fixed = TRUE))%>%
  #filter(Operator == 'Aeroflot') %>%
  mutate(Year = year(mdy(Date))) %>%
  group_by(Year)%>%
  summarise(Fatalities_num = sum(Fatalities))
temp_full4 <- data.frame(Year = seq(1945,2010,1))
temp_full4 <- merge(temp_full4, temp_fatalities, all.x=TRUE)
temp_full4$Fatalities_num[is.na(temp_full4$Fatalities_num)] <- 0

# number of aboard 

temp_fatalities_Aeroflot <- dataNoNA %>%
  #filter(!grepl("Military", Operator, fixed = TRUE))%>%
  filter(Operator == 'Aeroflot') %>%
  mutate(Year = year(mdy(Date))) %>%
  group_by(Year)%>%
  summarise(Fatalities_num_Aeroflot = sum(Fatalities))
temp_full5 <- data.frame(Year = seq(1945,2010,1))
temp_full5 <- merge(temp_full5, temp_fatalities_Aeroflot, all.x=TRUE)
temp_full5$Fatalities_num_Aeroflot[is.na(temp_full5$Fatalities_num_Aeroflot)] <- 0

#number of survive

temp_fatalities <- dataNoNA %>%
  filter(!grepl("Military", Operator, fixed = TRUE))%>%
  #filter(Operator == 'Aeroflot') %>%
  mutate(Year = year(mdy(Date))) %>%
  group_by(Year)%>%
  summarise(Survive_num = sum(Aboard-Fatalities))
temp_full6 <- data.frame(Year = seq(1945,2010,1))
temp_full6 <- merge(temp_full6, temp_fatalities, all.x=TRUE)
temp_full6$numAcc_full[is.na(temp_full6$Survive_num)] <- 0

```
```{r}
# since 1908 to 2009




```

```{r}
# world cloud for Aeroflot
library("tm")
library("SnowballC")
library("wordcloud")
library("RColorBrewer")
#pal = brewer.pal(9,"Blues")
data_Aeroflot_loc <- dataNoNA%>%
  filter(Operator == 'Aeroflot')%>%
  filter(Location != '')%>%
  filter(Summary != '')
 # filter(!is.na(Fatalities))
data_alloperator <- dataNoNA%>%
  filter(Location != '')%>%
  filter(Summary != '')





#Load the data as a corpus
docs_loc <- Corpus(VectorSource(data_Aeroflot_loc$Location))
docs_summary <- Corpus(VectorSource(data_Aeroflot_loc$Summary))
doc_allsummary <- Corpus(VectorSource(data_alloperator$Summary))

#Inspect the content of the document
inspect(docs_loc)
inspect(docs_summary)
inspect(doc_allsummary)
#Text transformation
#toSpace <- content_transformer(function (x , pattern ) gsub(pattern, " ", x))
#docs <- tm_map(docs, toSpace, ",")
#Cleaning the text
# Convert the text to lower case
docs_loc <- tm_map(docs_loc, content_transformer(tolower))
docs_summary <- tm_map(docs_summary, content_transformer(tolower))
doc_allsummary <- tm_map(doc_allsummary,content_transformer(tolower))
# Remove numbers
docs_loc <- tm_map(docs_loc, removeNumbers)
docs_summary <- tm_map(docs_summary, removeNumbers)
doc_allsummary <- tm_map(doc_allsummary, removeNumbers)
# Remove english common stopwords
docs_loc <- tm_map(docs_loc, removeWords, stopwords("english"))
docs_loc <- tm_map(docs_loc, removeWords, c("near"))
docs_summary <- tm_map(docs_summary, removeWords, stopwords("english"))
docs_summary <- tm_map(docs_summary, removeWords, c("aircraft","plane","flight"))
doc_allsummary <- tm_map(doc_allsummary, removeWords, stopwords("english"))
doc_allsummary<- tm_map(doc_allsummary, removeWords, c("aircraft","plane","flight"))

# Remove punctuations
docs_loc <- tm_map(docs_loc, removePunctuation)
docs_summary <- tm_map(docs_summary, removePunctuation)
doc_allsummary<- tm_map(doc_allsummary, removePunctuation)
# Eliminate extra white spaces
docs_loc <- tm_map(docs_loc, stripWhitespace)
docs_summary <- tm_map(docs_summary, stripWhitespace)
doc_allsummary <- tm_map(doc_allsummary, stripWhitespace)

# build world cloud
Location_fre <- TermDocumentMatrix(docs_loc)
Summary_fre <-TermDocumentMatrix(docs_summary)
allsummary_fre <- TermDocumentMatrix(doc_allsummary)
m_loc<- as.matrix(Location_fre)
m_summary<- as.matrix(Summary_fre)
m_all <- as.matrix(allsummary_fre)
v_loc <- sort(rowSums(m_loc),decreasing=TRUE)
v_summary <- sort(rowSums(m_summary),decreasing=TRUE)
v_all <- sort(rowSums(m_all),decreasing=TRUE)
d_loc <- data.frame(word = names(v_loc),freq=v_loc)
d_summary <- data.frame(word = names(v_summary),freq=v_summary)
d_all <- data.frame(word = names(v_all),freq=v_all)
head(d_loc, 10)
head(d_summary, 10)
head(d_all,10)
# generate the word cloud
set.seed(1234)
wordcloud(words = d_loc$word, freq = d_loc$freq, min.freq = 1,
          max.words=100, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))

wordcloud(words = d_summary$word, freq = d_summary$freq, min.freq = 1,
          max.words=100, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))

wordcloud(words = d_all$word, freq = d_all$freq, min.freq = 1,
          max.words=100, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))

```




```{r}
# number of accidents all airplane and Aeroflot
p <- ggplot(temp_full2, aes(x = Year))
  p <- p + geom_line(data = temp_full3, aes(y = numAcc_full , colour = 'ALL_Accidents'))
  p<- p + geom_vline(xintercept = 1973, linetype = 'dashed')
  # adding the relative humidity data, transformed to match roughly the range of the temperature
  #p <- p + geom_point(data = temp_full2,aes(y = Fatalities_num, colour = "black"))
  p<- p + geom_line(data = temp_full,aes(y = numAcc*6, colour = 'Accidents'))
  #p <- p + geom_point(data = temp_full, aes(y = numAcc*50, colour = 'black'))
  # now adding the secondary axis, following the example in the help file ?scale_y_continuous
  # and, very important, reverting the above transformation
  p <- p + scale_y_continuous(name = "num_Fatalities", sec.axis =  sec_axis((~ . / 6), name = "num_ACC"))
  p <- p + scale_x_continuous(breaks=seq(1945, 2010,5)) + theme_classic()
  p <- p +  ggtitle("Aeroflot") + theme(plot.title = element_text(hjust = 0.5))
  # modifying colours and theme options
  p <- p + scale_colour_manual(values = c("blue", "red","black","green"))
  #p<- p +theme(legend.position = "none")
  #p <- p + labs(y = "Air temperature [°C]",
               # x = "Date and time",
               # colour = "Parameter")
 # p <- p + theme(legend.position = c(0.8, 0.9))


p


#  fatalities all airplane and Aeroflot
p_f <- ggplot(temp_full5, aes(x = Year))
  p_f <- p_f + geom_line(data = temp_full4, aes(y = Fatalities_num , colour = 'ALL_Accidents'))
  #p<- p + geom_vline(xintercept = 1973, linetype = 'dashed')
  # adding the relative humidity data, transformed to match roughly the range of the temperature
  #p <- p + geom_point(data = temp_full2,aes(y = Fatalities_num, colour = "black"))
  p_f<- p_f + geom_line(data = temp_full5,aes(y = Fatalities_num_Aeroflot*3, colour = 'Accidents'))
  #p <- p + geom_point(data = temp_full, aes(y = numAcc*50, colour = 'black'))
  # now adding the secondary axis, following the example in the help file ?scale_y_continuous
  # and, very important, reverting the above transformation
  p_f <- p_f + scale_y_continuous(name = "num_Fatalities", sec.axis =  sec_axis((~ . / 3), name = "num_ACC"))
  p_f <- p_f + scale_x_continuous(breaks=seq(1945, 2010,5)) + theme_classic()
  p_f <- p_f +  ggtitle("Aeroflot") + theme(plot.title = element_text(hjust = 0.5))
  # modifying colours and theme options
  p_f <- p_f + scale_colour_manual(values = c("blue", "red","black","green"))


p_f




```
```{r}
library(stringr)
temp_loc <- dataNoNA %>%
  filter(Operator == 'Aeroflot') %>%
  mutate(Year = year(mdy(Date)))

temp_loc$Location <- sub(".*, ", "", temp_loc$Location)
temp_loc$Location<-str_replace_all(temp_loc$Location, fixed(" "), "")
temp_loc<-select(temp_loc, Location, Year)
temp_loc<- temp_loc[41:118,]
#temp_loc<- filter(temp_loc,Year ==c("1970","1971","1972","1973","1974","1975","1976","1977","1978","1979"))
fre <- temp_loc %>%
  group_by(Location) %>%
  summarise(location_frequent = n())
n = sum(fre$location_frequent)
n_R = 40
n_USSR = 22

library(ggmap) # for theme_nothing
df_1970s <- data.frame(value = c(16, 40, 22),
                 Group = c("OTHER location", "Russia", "USSR")) %>%
   # factor levels need to be the opposite order of the cumulative sum of the values
   mutate(Group = factor(Group, levels = c("USSR", "Russia", "OTHER location")),
          cumulative = cumsum(value),
          midpoint = cumulative - value / 2,
          label = paste0(Group, " ", round(value / sum(value) * 100, 1), "%"))

ggplot(df_1970s, aes(x = 1, weight = value, fill = Group)) +
   geom_bar(width = 1, position = "stack") +
   coord_polar(theta = "y") +
   geom_text(aes(x = 1.3, y = midpoint, label = label)) +
   theme_nothing()      

#newdata <- mtcars[order(mpg, -cyl),] 
#temp_loc<-filter(temp_loc, Location == 'Russia'|Location == 'USSR')
ggplot(temp_loc, aes(x = Year, fill=Location))+geom_histogram()+scale_x_continuous(breaks=seq(1970, 1979,1))+theme_classic()

```



