---
title: "Project2"
output: html_document
---

```{r}
library(dplyr)
library(ggplot2)
airplane<-read.csv("/Users/fudanvip/project2_IE6600/final-project-VS/Airplane_Crashes_and_Fatalities_Since_1908.csv",sep =",",stringsAsFactors = FALSE)
#str(airplane)
any(is.na(airplane$Date))
any(is.na(airplane$Location))
any(is.na(airplane$Operator))
any(is.na(airplane$Flight..))
any(is.na(airplane$Type))
any(is.na(airplane$Abord))
any(is.na(airplane$Fatalities))
any(is.na(airplane$Ground))
aboard_missing<-which(is.na(airplane$Aboard))
fatal_missing<-which(is.na(airplane$Fatalities))
ground_missing
fatal_missing
airplane[aboard_missing,]
airplane[fatal_missing,]
```

```{r}
#analysis whole data 
#the trend of aircrash after 1908, how many aircrash happened and how many people die in it. 
#thus, for this part visualization, we only use the data that fatalities and aboard are not na 
cleaned_trend<-subset(airplane, !is.na(Fatalities) & !is.na(Aboard) & Operator != "" & Type != "")
cleaned_trend$Date<-as.Date(cleaned_trend$Date, "%m/%d/%Y")
cleaned_trend$Year<- as.numeric(format(cleaned_trend$Date, format = "%Y"))
cleaned_trend$Month<- as.numeric(format(cleaned_trend$Date, format = "%m"))
cleaned_trend$Day<- as.numeric(format(cleaned_trend$Date, format = "%d"))
death<-summarise(group_by(cleaned_trend,Year),total_death = sum(Fatalities))
crash_num<-summarise(group_by(cleaned_trend,Year),total_crash = n())
arrange(crash_num,desc(total_crash))

ggplot(crash_num)+ geom_line(aes(x=Year, y=total_crash, color="pcs")) +labs(title="crash vs year")+scale_x_continuous(breaks = seq(1908,2009,by=3))+scale_y_continuous(breaks = seq(min(crash_num$total_crash),max(crash_num$total_crash),by=10))+theme(axis.text.x = element_text(angle=90),plot.title = element_text(hjust = 0.5))+ geom_segment(aes(x = 1972, y = 104, xend = 1972, yend = -Inf), linetype = 2)

ggplot(death)+ geom_line(aes(x=Year, y=total_death, color="pcs")) +labs(title="death vs year")+scale_x_continuous(breaks = seq(1908,2009,by=3))+scale_y_continuous(breaks = seq(min(death$total_death),max(death$total_death),by=500))+theme(axis.text.x = element_text(angle=90),plot.title = element_text(hjust = 0.5))

```

```{r}
#in this project, we want to know more about which operators happened air crash most offen and which type of air plane is most unsafe. Thus, we will subset data have both of these two most import inform and fatalities and Graound as main data set for analysis operator and type
#cleaned_data<-subset(airplane, Operator != "" & Type != "")
arrange(summarise(group_by(cleaned_trend,Operator),total_crash = n()),desc(total_crash))
top2<-subset(cleaned_trend,Operator=="Aeroflot" | Operator=="Military - U.S. Air Force")
#USAir<-subset(cleaned_trend,Operator=="Military - U.S. Air Force")
a<-summarise(group_by(top2,Year,Operator),crash=n())
arrange(a,desc(crash))
ggplot(a)+geom_line(aes(x=Year, y=crash, color=Operator))+scale_x_continuous(breaks = seq(min(a$Year),max(a$Year),by=5))+scale_y_continuous(breaks = seq(min(a$crash),max(a$crash),by=3))+ geom_segment(aes(x = 1973, y = 15, xend = 1973, yend = -Inf), linetype = 2)+ geom_segment(aes(x = 1952, y = 11, xend = 1952, yend = -Inf), linetype = 4)
```
```{r}
Aeroflot<-subset(cleaned_trend,Operator=="Aeroflot")
type<-arrange(summarise(group_by(Aeroflot,Type),crash=n()),desc(crash))[1:10,]

ggplot(Aeroflot)+geom_histogram(aes(x=Type),stat="count")+theme(axis.text.x = element_text(angle=90))
```